// DOM overlay: loading, title, letterbox, banners, hints, fades and the HUD shell.
export class UI {
  readonly root: HTMLElement;
  private loader: HTMLElement;
  private loaderBar: HTMLElement;
  private loaderLabel: HTMLElement;
  private title: HTMLElement;
  private letterTop: HTMLElement;
  private letterBot: HTMLElement;
  private banner: HTMLElement;
  private hint: HTMLElement;
  private fade: HTMLElement;
  private subtitle: HTMLElement;
  readonly hudRoot: HTMLElement;
  private bannerTimer = 0;
  private hintTimer = 0;

  constructor() {
    this.root = document.getElementById('ui')!;
    this.root.innerHTML = `
      <div class="fade" id="fade"></div>
      <div class="letterbox top" id="lbTop"></div>
      <div class="letterbox bot" id="lbBot"></div>
      <div id="hud"></div>
      <div class="banner" id="banner"></div>
      <div class="subtitle" id="subtitle"></div>
      <div class="hint" id="hint"></div>
      <div class="title" id="title">
        <div class="title-emblem"><div class="meteor"></div></div>
        <div class="title-main">FINAL FANTASY <span>VII</span></div>
        <div class="title-sub">R E B O R N</div>
        <div class="title-tag">a fan tribute · rendered in real time · every asset generated by code</div>
        <div class="title-press" id="titlePress">Click to begin</div>
        <div class="title-controls">
          <div><b>WASD</b> move · <b>Mouse</b> camera · <b>Shift</b> sprint · <b>Space</b> jump / dodge</div>
          <div><b>LMB</b> attack · <b>RMB</b> heavy · <b>1-4</b> materia · <b>Q</b> lock-on · <b>R</b> Limit Break · <b>F</b> mount</div>
        </div>
      </div>
      <div class="loader" id="loader">
        <div class="loader-title">FINAL FANTASY <span>VII</span> · REBORN</div>
        <div class="loader-track"><div class="loader-bar" id="loaderBar"></div></div>
        <div class="loader-label" id="loaderLabel">Awakening the Planet…</div>
      </div>`;
    const $ = (id: string) => document.getElementById(id)!;
    this.loader = $('loader');
    this.loaderBar = $('loaderBar');
    this.loaderLabel = $('loaderLabel');
    this.title = $('title');
    this.letterTop = $('lbTop');
    this.letterBot = $('lbBot');
    this.banner = $('banner');
    this.hint = $('hint');
    this.fade = $('fade');
    this.subtitle = $('subtitle');
    this.hudRoot = $('hud');
  }

  setLoading(p: number, label: string) {
    this.loaderBar.style.width = `${Math.round(p * 100)}%`;
    this.loaderLabel.textContent = label;
  }
  hideLoader() {
    this.loader.classList.add('hidden');
  }
  showTitle(v: boolean) {
    this.title.classList.toggle('visible', v);
  }
  setTitlePrompt(text: string) {
    document.getElementById('titlePress')!.textContent = text;
  }
  letterbox(v: number) {
    const h = `${(v * 11).toFixed(2)}vh`;
    this.letterTop.style.height = h;
    this.letterBot.style.height = h;
  }
  /** Show a big dramatic banner (e.g. LIMIT BREAK). */
  showBanner(text: string, cls = '', seconds = 2.5) {
    this.banner.className = 'banner show ' + cls;
    this.banner.innerHTML = text;
    this.bannerTimer = seconds;
  }
  showHint(html: string, seconds = 4) {
    this.hint.innerHTML = html;
    this.hint.classList.add('show');
    this.hintTimer = seconds;
  }
  hideHint() {
    this.hint.classList.remove('show');
    this.hintTimer = 0;
  }
  showSubtitle(text: string) {
    this.subtitle.textContent = text;
    this.subtitle.classList.toggle('show', !!text);
  }
  setFade(amount: number, color = '#000') {
    this.fade.style.background = color;
    this.fade.style.opacity = String(Math.max(0, Math.min(1, amount)));
  }

  update(dt: number) {
    if (this.bannerTimer > 0) {
      this.bannerTimer -= dt;
      if (this.bannerTimer <= 0) this.banner.classList.remove('show');
    }
    if (this.hintTimer > 0) {
      this.hintTimer -= dt;
      if (this.hintTimer <= 0) this.hint.classList.remove('show');
    }
  }
}
